version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"